python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/user/LaMP_1/train_questions.json --lamp_output_addr ./data_raw/user/LaMP_1/train_outputs.json
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/time/LaMP_1/train_questions.json" --lamp_output_addr ./data_raw/time/LaMP_1/train_outputs.json"
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/user/LaMP_1/dev_questions.json --lamp_output_addr ./data_raw/user/LaMP_1/dev_outputs.json
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/time/LaMP_1/dev_questions.json" --lamp_output_addr ./data_raw/time/LaMP_1/dev_outputs.json"
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/user/LaMP_2/train_questions.json --lamp_output_addr ./data_raw/user/LaMP_2/train_outputs.json
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/time/LaMP_2/train_questions.json" --lamp_output_addr ./data_raw/time/LaMP_2/train_outputs.json"
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/user/LaMP_2/dev_questions.json --lamp_output_addr ./data_raw/user/LaMP_2/dev_outputs.json
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/time/LaMP_2/dev_questions.json" --lamp_output_addr ./data_raw/time/LaMP_2/dev_outputs.json"
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/user/LaMP_3/train_questions.json --lamp_output_addr ./data_raw/user/LaMP_3/train_outputs.json
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/time/LaMP_3/train_questions.json" --lamp_output_addr ./data_raw/time/LaMP_3/train_outputs.json"
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/user/LaMP_3/dev_questions.json --lamp_output_addr ./data_raw/user/LaMP_3/dev_outputs.json
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/time/LaMP_3/dev_questions.json" --lamp_output_addr ./data_raw/time/LaMP_3/dev_outputs.json"
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/user/LaMP_4/train_questions.json --lamp_output_addr ./data_raw/user/LaMP_4/train_outputs.json
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/time/LaMP_4/train_questions.json" --lamp_output_addr ./data_raw/time/LaMP_4/train_outputs.json"
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/user/LaMP_4/dev_questions.json --lamp_output_addr ./data_raw/user/LaMP_4/dev_outputs.json
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/time/LaMP_4/dev_questions.json" --lamp_output_addr ./data_raw/time/LaMP_4/dev_outputs.json"
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/user/LaMP_5/train_questions.json --lamp_output_addr ./data_raw/user/LaMP_5/train_outputs.json
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/time/LaMP_5/train_questions.json" --lamp_output_addr ./data_raw/time/LaMP_5/train_outputs.json"
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/user/LaMP_5/dev_questions.json --lamp_output_addr ./data_raw/user/LaMP_5/dev_outputs.json
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/time/LaMP_5/dev_questions.json" --lamp_output_addr ./data_raw/time/LaMP_5/dev_outputs.json"
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/user/LaMP_7/train_questions.json --lamp_output_addr ./data_raw/user/LaMP_7/train_outputs.json
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/time/LaMP_7/train_questions.json" --lamp_output_addr ./data_raw/time/LaMP_7/train_outputs.json"
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/user/LaMP_7/dev_questions.json --lamp_output_addr ./data_raw/user/LaMP_7/dev_outputs.json
python3 utils/merge_with_rank.py --lamp_questions_addr ./data_raw/time/LaMP_7/dev_questions.json" --lamp_output_addr ./data_raw/time/LaMP_7/dev_outputs.json"